[package]
rust-version.workspace = true
name = "sdkwork-community-storage-sqlx-rust"
version.workspace = true
edition.workspace = true


[lints]
workspace = true
[lib]
name = "sdkwork_community_storage_sqlx"
path = "src/lib.rs"

[features]
default = []
test-support = []

[dependencies]
chrono.workspace = true
sdkwork-community-database-host.workspace = true
sdkwork-database-config.workspace = true
sdkwork-database-sqlx.workspace = true
sdkwork-utils-rust.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx = { workspace = true, features = ["json", "runtime-tokio", "postgres"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
